trigger:
  branches:
    include:
      - "*"
pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: yarn install
      displayName: install
    - script: yarn run build
      displayName: build
    - publish: build
      artifact: neural-recognition-gui-build
      displayName: publish build artifact
    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/neural-recognition-gui'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
- stage: UpdateService
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/neural-recognition-gui:$(Build.BuildId) neural-recognition-gui_app'
                readyTimeout: '20000'
