pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: yarn install
      displayName: install
    - script: yarn run build
      displayName: build
    - publish: build
      artifact: neural-recognition-gui-build
      displayName: publish build artifact
    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/neural-recognition-gui'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest-build
          displayName: publish build artifact

