trigger:
  - master
  - develop

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - script: yarn install
    - script: yarn run build
